USE [master]
GO

/****** Object:  Database [PersonsRepository]    Script Date: 23/10/2014 13:45:34 ******/
CREATE DATABASE [PersonsRepository] ON  PRIMARY 
( NAME = N'PersonsRepository', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\PersonsRepository.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PersonsRepository_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\PersonsRepository_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PersonsRepository] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PersonsRepository].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PersonsRepository] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PersonsRepository] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PersonsRepository] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PersonsRepository] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PersonsRepository] SET ARITHABORT OFF 
GO

ALTER DATABASE [PersonsRepository] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PersonsRepository] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PersonsRepository] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PersonsRepository] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PersonsRepository] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PersonsRepository] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PersonsRepository] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PersonsRepository] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PersonsRepository] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PersonsRepository] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PersonsRepository] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PersonsRepository] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PersonsRepository] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PersonsRepository] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PersonsRepository] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PersonsRepository] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PersonsRepository] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PersonsRepository] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PersonsRepository] SET  MULTI_USER 
GO

ALTER DATABASE [PersonsRepository] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PersonsRepository] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PersonsRepository] SET  READ_WRITE 
GO


